# Generated by Django 4.2.6 on 2023-10-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='countlike',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
