# Generated by Django 4.2.6 on 2023-10-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_postmodel_countlike_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
